### ISSUE TITLE
[Feature request]: Add support for OPENVOXDB_POSTGRES_PASSWORD_FILE env var

### ISSUE THREAD

**Issue by mdechiaro** [OpenVoxProject/container-openvoxdb#6]
### Use Case

This environment varable would support [secrets](https://docs.docker.com/compose/how-tos/use-secrets/#advanced) in a docker compose setup. The postgres container and puppetdb container can share the secret for ease of use. Here is an example config:

```
---
services:
  postgres:
    environment:
      POSTGRES_PASSWORD_FILE: "/run/secrets/db_password"
    secrets:
    - db_password
  puppetdb:
    environment:
      OPENVOXDB_POSTGRES_PASSWORD_FILE: "/run/secrets/db_password"
    secrets:
    - db_password
secrets:
  db_password:
    file: "/path/to/db_password"
```

### Describe the solution you would like

A shell function would need to be added `docker-entrypoint.d` that can read `/run/secrets/db_password` and set `OPENVOXDB_POSTGRES_PASSWORD` with the password.

### Additional context

The [postgres](https://hub.docker.com/_/postgres) image supports this `_FILE` feature with the following variables. For this request, I believe the password env var is most important.

```
POSTGRES_INITDB_ARGS
POSTGRES_PASSWORD
POSTGRES_USER
POSTGRES_DB
```
